import os
import logging
from datetime import datetime
from typing import List, Dict, Optional
from docx import Document
from docx.shared import Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.table import WD_TABLE_ALIGNMENT
from sqlalchemy.orm import Session
from database import get_db
from models import ComponentSelection
from config import settings
import uuid

logger = logging.getLogger(__name__)

class ReportService:
    def __init__(self):
        self.output_dir = settings.OUTPUT_DIR
        self._ensure_output_dir()
    
    def _ensure_output_dir(self):
        """Create output directory if it doesn't exist"""
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)
    
    def generate_procurement_report(self, session_id: str) -> Dict:
        """Generate Word document procurement report"""
        try:
            # Get selections for the session
            selections = self._get_session_selections(session_id)
            
            if not selections:
                return {
                    "status": "error",
                    "message": "No product selections found for this session"
                }
            
            # Generate report
            filename = f"procurement_report_{session_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
            filepath = os.path.join(self.output_dir, filename)
            
            # Create Word document
            doc = self._create_report_document(selections, session_id)
            
            # Save document
            doc.save(filepath)
            
            logger.info(f"Report generated: {filepath}")
            
            return {
                "status": "success",
                "message": "Procurement report generated successfully",
                "filename": filename,
                "filepath": filepath,
                "download_url": f"/api/reports/download/{filename}"
            }
            
        except Exception as e:
            logger.error(f"Error generating procurement report: {e}")
            return {
                "status": "error",
                "message": f"Error generating report: {str(e)}"
            }
    
    def _get_session_selections(self, session_id: str) -> List[Dict]:
        """Get all selections for a session"""
        try:
            db = next(get_db())
            
            selections = db.query(ComponentSelection).filter(
                ComponentSelection.session_id == session_id
            ).all()
            
            result = []
            for selection in selections:
                component = selection.component
                product = selection.product
                
                result.append({
                    "component_name": component.name,
                    "product_name": product.name,
                    "price": product.price,
                    "seller": product.seller,
                    "rating": product.rating,
                    "review_count": product.review_count,
                    "product_link": product.product_link,
                    "selected_at": selection.created_at
                })
            
            return result
            
        except Exception as e:
            logger.error(f"Error getting session selections: {e}")
            return []
        finally:
            db.close()
    
    def _create_report_document(self, selections: List[Dict], session_id: str) -> Document:
        """Create Word document with procurement report"""
        doc = Document()
        
        # Add title
        title = doc.add_heading('Component Procurement Report', 0)
        title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        # Add metadata
        doc.add_paragraph(f"Session ID: {session_id}")
        doc.add_paragraph(f"Generated on: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
        doc.add_paragraph(f"Total Components: {len(selections)}")
        
        # Add horizontal line
        doc.add_paragraph("=" * 50)
        
        # Add summary section
        self._add_summary_section(doc, selections)
        
        # Add detailed selections table
        self._add_selections_table(doc, selections)
        
        # Add cost analysis
        self._add_cost_analysis(doc, selections)
        
        # Add recommendations
        self._add_recommendations(doc, selections)
        
        # Add footer
        footer = doc.add_paragraph()
        footer.add_run("Generated by comp-HQ - AI-Powered Component Sourcing Assistant").italic = True
        footer.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
        
        return doc
    
    def _add_summary_section(self, doc: Document, selections: List[Dict]):
        """Add executive summary section"""
        doc.add_heading('Executive Summary', level=1)
        
        total_cost = sum(s['price'] for s in selections if s['price'])
        avg_rating = sum(s['rating'] for s in selections if s['rating']) / len([s for s in selections if s['rating']]) if any(s['rating'] for s in selections) else 0
        
        summary = doc.add_paragraph()
        summary.add_run(f"This procurement report contains ").bold = True
        summary.add_run(f"{len(selections)} ")
        summary.add_run(f"selected components with a total estimated cost of ").bold = True
        summary.add_run(f"${total_cost:.2f}. ")
        
        if avg_rating > 0:
            summary.add_run(f"The average product rating is ").bold = True
            summary.add_run(f"{avg_rating:.1f}/5.0 ")
            summary.add_run(f"indicating high-quality selections.")
        
        doc.add_paragraph()  # Add spacing
    
    def _add_selections_table(self, doc: Document, selections: List[Dict]):
        """Add detailed selections table"""
        doc.add_heading('Selected Components', level=1)
        
        # Create table
        table = doc.add_table(rows=1, cols=6)
        table.style = 'Table Grid'
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        
        # Set headers
        headers = ['Component', 'Product Name', 'Seller', 'Price', 'Rating', 'Reviews']
        header_cells = table.rows[0].cells
        
        for i, header in enumerate(headers):
            header_cells[i].text = header
            header_cells[i].paragraphs[0].runs[0].bold = True
        
        # Add data rows
        for selection in selections:
            row = table.add_row().cells
            row[0].text = selection['component_name']
            row[1].text = selection['product_name']
            row[2].text = selection['seller']
            row[3].text = f"${selection['price']:.2f}" if selection['price'] else "N/A"
            row[4].text = f"{selection['rating']}/5" if selection['rating'] else "N/A"
            row[5].text = str(selection['review_count']) if selection['review_count'] else "N/A"
        
        doc.add_paragraph()  # Add spacing
    
    def _add_cost_analysis(self, doc: Document, selections: List[Dict]):
        """Add cost analysis section"""
        doc.add_heading('Cost Analysis', level=1)
        
        # Calculate statistics
        prices = [s['price'] for s in selections if s['price']]
        
        if prices:
            total_cost = sum(prices)
            avg_cost = total_cost / len(prices)
            min_cost = min(prices)
            max_cost = max(prices)
            
            # Create cost breakdown
            cost_para = doc.add_paragraph()
            cost_para.add_run("Cost Breakdown:\n").bold = True
            cost_para.add_run(f"• Total Cost: ${total_cost:.2f}\n")
            cost_para.add_run(f"• Average Cost per Component: ${avg_cost:.2f}\n")
            cost_para.add_run(f"• Lowest Cost Component: ${min_cost:.2f}\n")
            cost_para.add_run(f"• Highest Cost Component: ${max_cost:.2f}")
            
            # Find most expensive component
            most_expensive = max(selections, key=lambda x: x['price'] if x['price'] else 0)
            doc.add_paragraph(f"\nMost Expensive: {most_expensive['component_name']} - {most_expensive['product_name']} (${most_expensive['price']:.2f})")
            
            # Find least expensive component
            least_expensive = min([s for s in selections if s['price']], key=lambda x: x['price'])
            doc.add_paragraph(f"Least Expensive: {least_expensive['component_name']} - {least_expensive['product_name']} (${least_expensive['price']:.2f})")
        
        doc.add_paragraph()  # Add spacing
    
    def _add_recommendations(self, doc: Document, selections: List[Dict]):
        """Add recommendations section"""
        doc.add_heading('Recommendations', level=1)
        
        recommendations = []
        
        # Analyze ratings
        low_rated = [s for s in selections if s['rating'] and s['rating'] < 3.5]
        if low_rated:
            recommendations.append(f"• {len(low_rated)} component(s) have ratings below 3.5/5. Consider reviewing these selections for quality concerns.")
        
        # Analyze costs
        prices = [s['price'] for s in selections if s['price']]
        if prices and max(prices) > (sum(prices) / len(prices)) * 2:
            recommendations.append("• One or more components are significantly more expensive than the average. Consider if premium features justify the cost.")
        
        # Analyze sellers
        sellers = [s['seller'] for s in selections]
        unique_sellers = set(sellers)
        if len(unique_sellers) == 1:
            recommendations.append(f"• All components are from a single seller ({list(unique_sellers)[0]}). Consider diversifying suppliers for better pricing and availability.")
        elif len(unique_sellers) > 3:
            recommendations.append("• Components are sourced from multiple sellers. This may help with availability but consider shipping costs and consolidation opportunities.")
        
        # General recommendations
        recommendations.append("• Verify product specifications match your project requirements before finalizing purchases.")
        recommendations.append("• Check lead times and availability, especially for specialized components.")
        recommendations.append("• Consider ordering spare components for critical parts to avoid project delays.")
        
        # Add recommendations to document
        for rec in recommendations:
            doc.add_paragraph(rec)
        
        doc.add_paragraph()  # Add spacing
    
    def get_report_file(self, filename: str) -> Optional[str]:
        """Get report file path for download"""
        filepath = os.path.join(self.output_dir, filename)
        if os.path.exists(filepath):
            return filepath
        return None
    
    def list_reports(self) -> List[Dict]:
        """List all available reports"""
        try:
            reports = []
            for filename in os.listdir(self.output_dir):
                if filename.endswith('.docx') and filename.startswith('procurement_report_'):
                    filepath = os.path.join(self.output_dir, filename)
                    stat = os.stat(filepath)
                    
                    # Extract session_id from filename
                    parts = filename.replace('procurement_report_', '').replace('.docx', '').split('_')
                    session_id = parts[0] if parts else 'unknown'
                    
                    reports.append({
                        'filename': filename,
                        'session_id': session_id,
                        'created_at': datetime.fromtimestamp(stat.st_ctime),
                        'size': stat.st_size,
                        'download_url': f"/api/reports/download/{filename}"
                    })
            
            # Sort by creation date (newest first)
            reports.sort(key=lambda x: x['created_at'], reverse=True)
            return reports
            
        except Exception as e:
            logger.error(f"Error listing reports: {e}")
            return []
